### ISSUE TITLE
'module' object has no attribute 'sha3_256'

### ISSUE THREAD

**Issue by lawup** [nebulasio/neb.py#8]
Traceback (most recent call last):
  File "tmp.py", line 18, in <module>
    account = Account.new_account()
  File "/usr/local/lib/python3.4/dist-packages/nebpysdk/src/account/Account.py", line 33, in new_account
    return Account(private_key)
  File "/usr/local/lib/python3.4/dist-packages/nebpysdk/src/account/Account.py", line 23, in __init__
    self.__address = Address.new_address_from_pub_key(self.__publickey.encode())
  File "/usr/local/lib/python3.4/dist-packages/nebpysdk/src/core/Address.py", line 105, in new_address_from_pub_key
    return cls.new_address(cls.AddressType.ACCOUNT, pub)
  File "/usr/local/lib/python3.4/dist-packages/nebpysdk/src/core/Address.py", line 81, in new_address
    sha3_256_value = hashlib.sha3_256()
AttributeError: 'module' object has no attribute 'sha3_256'

**Comment by lawup** [comment]
hashlib下根本没有sha3_256()

**Comment by benedikt90** [comment]
Would you mind sharing the solution to this?

Edit: was able to find it myself: python3 needed
