### ISSUE TITLE
could not install neb through pip install neb-py

### ISSUE THREAD

**Issue by spiritmg** [nebulasio/neb.py#9]
this is the log，and i have no ideal about what is wrong because i am a python beginner.
maybe eth-hash has wrong，i can install eth-hash0.1.4, but the neb-py use eth-hash0.1.3, i could not install this。(i use python2.7 on win10)
****
```
Collecting neb-py
  Using cached https://files.pythonhosted.org/packages/d5/ec/3ac26ea9319ab3bb6a77dd3bbbe1044111f9a94d0ab3c2f72b70ae83e8e2/neb-py-0.4.1.tar.gz
Collecting certifi==2018.4.16 (from neb-py)
  Using cached https://files.pythonhosted.org/packages/7c/e6/92ad559b7192d846975fc916b65f667c7b8c3a32bea7372340bfe9a15fa5/certifi-2018.4.16-py2.py3-none-any.whl
Requirement already satisfied: chardet==3.0.4 in c:\python27\lib\site-packages (from neb-py) (3.0.4)
Collecting Crypto==1.4.1 (from neb-py)
  Using cached https://files.pythonhosted.org/packages/fc/bb/0b812dc02e6357606228edfbf5808f5ca0a675a84273578c3a199e841cd8/crypto-1.4.1-py2.py3-none-any.whl
Collecting cytoolz==0.9.0.1 (from neb-py)
  Using cached https://files.pythonhosted.org/packages/36/f4/9728ba01ccb2f55df9a5af029b48ba0aaca1081bbd7823ea2ee223ba7a42/cytoolz-0.9.0.1.tar.gz
Collecting eth-hash==0.1.3 (from neb-py)
  Using cached https://files.pythonhosted.org/packages/db/ce/16293ee4ed1ccc5de265e11f7ecd21ba054cdeb9f601bde50eb72c1aac62/eth-hash-0.1.3.tar.gz
    Complete output from command python setup.py egg_info:

    Installed c:\users\lenovo\appdata\local\temp\pip-install-wm6abh\eth-hash\.eggs\setuptools_markdown-0.2-py2.7.egg
    Searching for pypandoc
    Reading https://pypi.python.org/simple/pypandoc/
    Best match: pypandoc 1.4
    Downloading https://files.pythonhosted.org/packages/71/81/00184643e5a10a456b4118fc12c96780823adb8ed974eb2289f29703b29b/pypandoc-1.4.tar.gz#sha256=e914e6d5f84a76764887e4d909b09d63308725f0cbb5293872c2c92f07c11a5b
    Processing pypandoc-1.4.tar.gz
    Writing c:\users\lenovo\appdata\local\temp\easy_install-0zuffb\pypandoc-1.4\setup.cfg
    Running pypandoc-1.4\setup.py -q bdist_egg --dist-dir c:\users\lenovo\appdata\local\temp\easy_install-0zuffb\pypandoc-1.4\egg-dist-tmp-hmsuig
    See http://johnmacfarlane.net/pandoc/installing.html
    for installation options
    ---------------------------------------------------------------

    **zip_safe flag not set; analyzing archive contents...
    pypandoc.__init__: module references __file__


    !!! pandoc not found, long_description is bad, don't upload this to PyPI !!!**


    creating c:\users\lenovo\appdata\local\temp\pip-install-wm6abh\eth-hash\.eggs\pypandoc-1.4-py2.7.egg
    Extracting pypandoc-1.4-py2.7.egg to c:\users\lenovo\appdata\local\temp\pip-install-wm6abh\eth-hash\.eggs

    Installed c:\users\lenovo\appdata\local\temp\pip-install-wm6abh\eth-hash\.eggs\pypandoc-1.4-py2.7.egg
    Searching for wheel>=0.25.0
    Reading https://pypi.python.org/simple/wheel/
    Best match: wheel 0.31.1
    Downloading https://files.pythonhosted.org/packages/2a/fb/aefe5d5dbc3f4fe1e815bcdb05cbaab19744d201bbc9b59cfa06ec7fc789/wheel-0.31.1.tar.gz#sha256=0a2e54558a0628f2145d2fc822137e322412115173e8a2ddbe1c9024338ae83c
    Processing wheel-0.31.1.tar.gz
    Writing c:\users\lenovo\appdata\local\temp\easy_install-tlceal\wheel-0.31.1\setup.cfg
    Running wheel-0.31.1\setup.py -q bdist_egg --dist-dir c:\users\lenovo\appdata\local\temp\easy_install-tlceal\wheel-0.31.1\egg-dist-tmp-mvh4do
    c:\python27\lib\distutils\dist.py:267: UserWarning: Unknown distribution option: 'python_requires'
      warnings.warn(msg)
    **warning: no files found matching 'wheel\*.txt'**
   ** warning: no files found matching '*.sh'**
    **warning: no files found matching '*.py' under directory 'wheel\test'**
    **warning: no files found matching 'wheel\test\test-1.0-py2.py3-none-win32.whl'**
   ** warning: no files found matching 'wheel\test\headers.dist\header.h'
    warning: no files found matching 'wheel\test\pydist-schema.json'
    no previously-included directories found matching 'wheel\test\*\dist'
    no previously-included directories found matching 'wheel\test\*\build'**
    creating c:\users\lenovo\appdata\local\temp\pip-install-wm6abh\eth-hash\.eggs\wheel-0.31.1-py2.7.egg
    Extracting wheel-0.31.1-py2.7.egg to c:\users\lenovo\appdata\local\temp\pip-install-wm6abh\eth-hash\.eggs

    Installed c:\users\lenovo\appdata\local\temp\pip-install-wm6abh\eth-hash\.eggs\wheel-0.31.1-py2.7.egg
    c:\python27\lib\distutils\dist.py:267: UserWarning: Unknown distribution option: 'python_requires'
      warnings.warn(msg)
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "c:\users\lenovo\appdata\local\temp\pip-install-wm6abh\eth-hash\setup.py", line 72, in <module>
        'Programming Language :: Python :: Implementation :: PyPy',
      File "c:\python27\lib\distutils\core.py", line 111, in setup
        _setup_distribution = dist = klass(attrs)
      File "c:\python27\lib\site-packages\setuptools\dist.py", line 272, in __init__
        _Distribution.__init__(self,attrs)
      File "c:\python27\lib\distutils\dist.py", line 287, in __init__
        self.finalize_options()
      File "c:\python27\lib\site-packages\setuptools\dist.py", line 327, in finalize_options
        ep.load()(self, ep.name, value)
      File "c:\users\lenovo\appdata\local\temp\pip-install-wm6abh\eth-hash\.eggs\setuptools_markdown-0.2-py2.7.egg\setuptools_markdown.py", line 22, in long_description_markdown_filename
        output = pypandoc.convert(markdown_filename, 'rst')
      File "c:\users\lenovo\appdata\local\temp\pip-install-wm6abh\eth-hash\.eggs\pypandoc-1.4-py2.7.egg\pypandoc\__init__.py", line 66, in convert
        raise RuntimeError("Format missing, but need one (identified source as text as no "
    **RuntimeError: Format missing, but need one (identified source as text as no file with that name was found).**

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in c:\users\xxx\appdata\local\temp\pip-install-wm6abh\eth-hash\
```

**Comment by spiritmg** [comment]
i changed "eth-hash == 0.1.3" to "eth-hash == 0.1.4" in setup.py, but when i import neb-py ,there still have something wrong!

```
>>> from nebpysdk.src.account.Account import Account
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "nebpysdk\src\account\Account.py", line 25
    def set_privatekey(self, pri_key_str: str):
                                        ^
SyntaxError: invalid syntax
```

**Comment by yupnano** [comment]
The SyntaxError is result from "type hints", which is a syntax of python3.
Please use python3 to run neb-py code.

**Comment by spiritmg** [comment]
@yupnano thank you!

i tried python 3.7, but neb-py require pycurl, and pycurl can not work with python3.7, it can work with python3.5 3.6.
so i download python3.6.6 , and reinstall neb-py, it shows:
 " error: Microsoft Visual C++ 14.0 is required. Get it with "Microsoft Visual C++ Build Tools": http://landinghub.visualstudio.com/visual-cpp-build-tools" (the visual-cpp-build-tools is so big about 4GB. ), 
the error is happened when the pytoolz installed, so i find a  whl (cytoolz-0.9.0.1-cp36-cp36m-win_amd64.whl) package, and it works.

**now, the neb-py has installed success!**
